name: Keep Codespace Running
on:
  schedule:
    - cron: '*/1 * * * *'  
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run the script
        run: |
          echo "Running script..."
          python bot.py  # Replace with your actual command
